// Code generated by origingen rpc; DO NOT EDIT.

package rpcfixture

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	time "time"
)

const (
	_ uint = rpc.GeneratedABIVersion - 2
	_ uint = 2 - rpc.GeneratedABIVersion
)

const playerRPCContractID rpc.ContractID = 0xb3ca21d38db4b2fc

var playerRPCFingerprint = rpc.ContractFingerprint{0x4a, 0x2d, 0x6b, 0x81, 0x4c, 0xdb, 0xba, 0x84, 0xb1, 0xff, 0xbe, 0xd6, 0x89, 0x8a, 0xd5, 0x4a, 0x8a, 0x8e, 0xd4, 0x46, 0xb0, 0xee, 0x45, 0x13, 0x36, 0x35, 0xe0, 0x5c, 0xc9, 0xa8, 0x1d, 0x1b}

const playerRPCEchoNameMethodID rpc.MethodID = 0xb441ccb1960cd3b9
const playerRPCGetPlayerMethodID rpc.MethodID = 0x0612b3cda06ad14b
const playerRPCPlayerOnlineMethodID rpc.MethodID = 0xafc4908eabe03c37
const playerRPCRoundTripBlobMethodID rpc.MethodID = 0x28b2541698611f17
const playerRPCRoundTripPackedIDMethodID rpc.MethodID = 0xbb4af7338fe6f3a4
const playerRPCRoundTripTimeMethodID rpc.MethodID = 0x78c2194a36266c4e
const playerRPCSavePlayerMethodID rpc.MethodID = 0x5f67ae07657409b1

// PlayerRPCClient 是 github.com/duanhf2012/origin/v3/tests/integration/rpcfixture.PlayerRPC 的强类型生成客户端。
type PlayerRPCClient struct {
	client rpc.Client
}

// NewPlayerRPCClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewPlayerRPCClient(owner service.IService, target rpc.Target) PlayerRPCClient {
	return PlayerRPCClient{client: rpc.NewGeneratedClient(owner, target, playerRPCContractID, playerRPCFingerprint)}
}

// BindPlayerRPC 使用契约默认 ServiceName "PlayerService" 绑定轻量客户端。
func BindPlayerRPC(owner service.IService) PlayerRPCClient {
	return NewPlayerRPCClient(owner, rpc.ToService("PlayerService"))
}

// BindPlayerRPCTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindPlayerRPCTo(owner service.IService, serviceName string) PlayerRPCClient {
	return NewPlayerRPCClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client PlayerRPCClient) OnNode(nodeID string) PlayerRPCClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client PlayerRPCClient) RouteRoundRobin() PlayerRPCClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client PlayerRPCClient) RouteRandom() PlayerRPCClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client PlayerRPCClient) Route(key any) PlayerRPCClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client PlayerRPCClient) RouteBy(selector rpc.RouteSelector) PlayerRPCClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// encodePlayerRPCEchoNameRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCEchoNameRequest(client rpc.Client, kind rpc.CallKind, arg1 string) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCEchoNameRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCEchoNameRequest(data []byte) (arg1 string, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCEchoNameResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCEchoNameResponse(response *rpc.ResponseWriter, result1 string) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1)); err != nil {
		return err
	}
	return writer.Done()
}

// decodePlayerRPCEchoNameResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCEchoNameResponse(data []byte) (result1 string, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// AwaitEchoName 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitEchoName(ctx context.Context, arg1 string) (result1 string, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCEchoNameMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCEchoNameRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCEchoNameMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCEchoNameResponse(data)
		return err
	})
	return
}

// AsyncEchoName 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncEchoName(ctx context.Context, arg1 string, callback func(context.Context, string, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCEchoNameMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCEchoNameRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCEchoNameMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(string), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCEchoNameResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyEchoName 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyEchoName(ctx context.Context, arg1 string) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCEchoNameMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCEchoNameRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCEchoNameMethodID, request)
}

// BroadcastEchoName 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastEchoName(ctx context.Context, arg1 string) error {
	request, err := encodePlayerRPCEchoNameRequest(client.client, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCEchoNameMethodID, request)
}

// encodePlayerRPCGetPlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCGetPlayerRequest(client rpc.Client, kind rpc.CallKind, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg2.Name)); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg2.Score != nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg2.Tags), arg2.Tags == nil); err != nil {
		return nil, err
	}
	for index1 := range arg2.Tags {
		if err := sizer.AddString(string(arg2.Tags[index1])); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg2.Metadata), arg2.Metadata == nil); err != nil {
		return nil, err
	}
	for key2, value3 := range arg2.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return nil, err
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return nil, err
			}
		}
	}
	if err := sizer.AddBytes([]byte(arg2.Payload)); err != nil {
		return nil, err
	}
	if arg3 == nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	} else {
		if err := sizer.AddProto(arg3); err != nil {
			return nil, err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt64(int64(arg2.ID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg2.Name)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WritePresence(arg2.Score != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg2.Score != nil {
		if err := writer.WriteInt32(int32((*arg2.Score))); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg2.Tags), arg2.Tags == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index4 := range arg2.Tags {
		if err := writer.WriteString(string(arg2.Tags[index4])); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg2.Metadata), arg2.Metadata == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for key5, value6 := range arg2.Metadata {
		if err := writer.WriteString(string(key5)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WritePresence(value6 != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if value6 != nil {
			if err := writer.WriteString(string((*value6).Value)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.WriteBytes([]byte(arg2.Payload)); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg3 == nil {
		if err := writer.WriteNil(); err != nil {
			buffer.Release()
			return nil, err
		}
	} else {
		if err := writer.WriteProto(arg3); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCGetPlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerRequest(data []byte) (arg1 int64, arg2 PlayerData, arg3 *structpb.Struct, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	var decoded2 int64
	decoded2, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg2.ID = int64(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg2.Name = string(decoded3)
	var present4 bool
	present4, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present4 {
		arg2.Score = (OptionalScore)(new(int32))
		var decoded5 int32
		decoded5, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*arg2.Score) = int32(decoded5)
	}
	var length6 int
	var isNil7 bool
	length6, isNil7, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length6, 4)
	if decodeErr != nil {
		return
	}
	if !isNil7 {
		arg2.Tags = make([]string, length6)
		for index8 := 0; index8 < length6; index8++ {
			var decoded9 string
			decoded9, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg2.Tags[index8] = string(decoded9)
		}
	}
	var length10 int
	var isNil11 bool
	length10, isNil11, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length10, 5)
	if decodeErr != nil {
		return
	}
	if !isNil11 {
		arg2.Metadata = make(map[string]*wrapperspb.StringValue, length10)
		for index12 := 0; index12 < length10; index12++ {
			var key13 string
			var value14 *wrapperspb.StringValue
			var decoded15 string
			decoded15, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key13 = string(decoded15)
			var present16 bool
			present16, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present16 {
				value14 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded17 string
				decoded17, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value14).Value = string(decoded17)
			}
			arg2.Metadata[key13] = value14
		}
	}
	var decoded18 []byte
	decoded18, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg2.Payload = []byte(decoded18)
	var payload19 []byte
	var isNil20 bool
	payload19, isNil20, decodeErr = reader.ReadProtoPayload()
	if decodeErr != nil {
		return
	}
	if !isNil20 {
		arg3 = new(structpb.Struct)
		decodeErr = rpc.UnmarshalProto(payload19, arg3, false)
		if decodeErr != nil {
			return
		}
	}
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCGetPlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCGetPlayerResponse(response *rpc.ResponseWriter, result1 PlayerData, result2 *structpb.Struct) error {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.Name)); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if result1.Score != nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.Tags), result1.Tags == nil); err != nil {
		return err
	}
	for index1 := range result1.Tags {
		if err := sizer.AddString(string(result1.Tags[index1])); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.Metadata), result1.Metadata == nil); err != nil {
		return err
	}
	for key2, value3 := range result1.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return err
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return err
			}
		}
	}
	if err := sizer.AddBytes([]byte(result1.Payload)); err != nil {
		return err
	}
	if result2 == nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
	} else {
		if err := sizer.AddProto(result2); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteInt64(int64(result1.ID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.Name)); err != nil {
		return err
	}
	if err := writer.WritePresence(result1.Score != nil); err != nil {
		return err
	}
	if result1.Score != nil {
		if err := writer.WriteInt32(int32((*result1.Score))); err != nil {
			return err
		}
	}
	if err := writer.WriteContainer(len(result1.Tags), result1.Tags == nil); err != nil {
		return err
	}
	for index4 := range result1.Tags {
		if err := writer.WriteString(string(result1.Tags[index4])); err != nil {
			return err
		}
	}
	if err := writer.WriteContainer(len(result1.Metadata), result1.Metadata == nil); err != nil {
		return err
	}
	for key5, value6 := range result1.Metadata {
		if err := writer.WriteString(string(key5)); err != nil {
			return err
		}
		if err := writer.WritePresence(value6 != nil); err != nil {
			return err
		}
		if value6 != nil {
			if err := writer.WriteString(string((*value6).Value)); err != nil {
				return err
			}
		}
	}
	if err := writer.WriteBytes([]byte(result1.Payload)); err != nil {
		return err
	}
	if result2 == nil {
		if err := writer.WriteNil(); err != nil {
			return err
		}
	} else {
		if err := writer.WriteProto(result2); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodePlayerRPCGetPlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerResponse(data []byte) (result1 PlayerData, result2 *structpb.Struct, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.ID = int64(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.Name = string(decoded2)
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		result1.Score = (OptionalScore)(new(int32))
		var decoded4 int32
		decoded4, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Score) = int32(decoded4)
	}
	var length5 int
	var isNil6 bool
	length5, isNil6, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length5, 4)
	if decodeErr != nil {
		return
	}
	if !isNil6 {
		result1.Tags = make([]string, length5)
		for index7 := 0; index7 < length5; index7++ {
			var decoded8 string
			decoded8, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			result1.Tags[index7] = string(decoded8)
		}
	}
	var length9 int
	var isNil10 bool
	length9, isNil10, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length9, 5)
	if decodeErr != nil {
		return
	}
	if !isNil10 {
		result1.Metadata = make(map[string]*wrapperspb.StringValue, length9)
		for index11 := 0; index11 < length9; index11++ {
			var key12 string
			var value13 *wrapperspb.StringValue
			var decoded14 string
			decoded14, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key12 = string(decoded14)
			var present15 bool
			present15, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present15 {
				value13 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded16 string
				decoded16, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value13).Value = string(decoded16)
			}
			result1.Metadata[key12] = value13
		}
	}
	var decoded17 []byte
	decoded17, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	result1.Payload = []byte(decoded17)
	var payload18 []byte
	var isNil19 bool
	payload18, isNil19, decodeErr = reader.ReadProtoPayload()
	if decodeErr != nil {
		return
	}
	if !isNil19 {
		result2 = new(structpb.Struct)
		decodeErr = rpc.UnmarshalProto(payload18, result2, true)
		if decodeErr != nil {
			return
		}
	}
	decodeErr = reader.Done()
	return
}

// AwaitGetPlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) (result1 PlayerData, result2 *structpb.Struct, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallRequest, arg1, arg2, arg3)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCGetPlayerMethodID, request, func(data []byte) error {
		result1, result2, err = decodePlayerRPCGetPlayerResponse(data)
		return err
	})
	return
}

// AsyncGetPlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct, callback func(context.Context, PlayerData, *structpb.Struct, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallRequest, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCGetPlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(PlayerData), *new(*structpb.Struct), callErr)
			return
		}
		result1, result2, decodeErr := decodePlayerRPCGetPlayerResponse(data)
		callback(callbackCtx, result1, result2, decodeErr)
	})
}

// NotifyGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallNotify, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCGetPlayerMethodID, request)
}

// BroadcastGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) error {
	request, err := encodePlayerRPCGetPlayerRequest(client.client, rpc.CallNotify, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCGetPlayerMethodID, request)
}

// encodePlayerRPCPlayerOnlineRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCPlayerOnlineRequest(client rpc.Client, kind rpc.CallKind, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCPlayerOnlineRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCPlayerOnlineRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// NotifyPlayerOnline 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyPlayerOnline(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCPlayerOnlineMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCPlayerOnlineRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCPlayerOnlineMethodID, request)
}

// BroadcastPlayerOnline 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastPlayerOnline(ctx context.Context, arg1 int64) error {
	request, err := encodePlayerRPCPlayerOnlineRequest(client.client, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCPlayerOnlineMethodID, request)
}

// encodePlayerRPCRoundTripBlobRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCRoundTripBlobRequest(client rpc.Client, kind rpc.CallKind, arg1 OwnedBlob) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := OwnedBlobCodec{}.Size(&(arg1))
	if customErr2 != nil {
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	customSize3, customErr4 := OwnedBlobCodec{}.Size(&(arg1))
	if customErr4 != nil {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	customPayload5, reserveErr6 := writer.ReserveCustom(customSize3)
	if reserveErr6 != nil {
		buffer.Release()
		return nil, reserveErr6
	}
	customWritten7, customErr8 := OwnedBlobCodec{}.MarshalTo(customPayload5, &(arg1))
	if customErr8 != nil || customWritten7 != len(customPayload5) {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCRoundTripBlobRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripBlobRequest(data []byte) (arg1 OwnedBlob, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := OwnedBlobCodec{}.Unmarshal(customPayload1, &(arg1))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCRoundTripBlobResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCRoundTripBlobResponse(response *rpc.ResponseWriter, result1 OwnedBlob) error {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := OwnedBlobCodec{}.Size(&(result1))
	if customErr2 != nil {
		return errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	customSize3, customErr4 := OwnedBlobCodec{}.Size(&(result1))
	if customErr4 != nil {
		return errs.ErrRPCEncodeFailed
	}
	customPayload5, reserveErr6 := writer.ReserveCustom(customSize3)
	if reserveErr6 != nil {
		return reserveErr6
	}
	customWritten7, customErr8 := OwnedBlobCodec{}.MarshalTo(customPayload5, &(result1))
	if customErr8 != nil || customWritten7 != len(customPayload5) {
		return errs.ErrRPCEncodeFailed
	}
	return writer.Done()
}

// decodePlayerRPCRoundTripBlobResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripBlobResponse(data []byte) (result1 OwnedBlob, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := OwnedBlobCodec{}.Unmarshal(customPayload1, &(result1))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	decodeErr = reader.Done()
	return
}

// AwaitRoundTripBlob 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitRoundTripBlob(ctx context.Context, arg1 OwnedBlob) (result1 OwnedBlob, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCRoundTripBlobMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCRoundTripBlobRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCRoundTripBlobMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCRoundTripBlobResponse(data)
		return err
	})
	return
}

// AsyncRoundTripBlob 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncRoundTripBlob(ctx context.Context, arg1 OwnedBlob, callback func(context.Context, OwnedBlob, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCRoundTripBlobMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripBlobRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCRoundTripBlobMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(OwnedBlob), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCRoundTripBlobResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyRoundTripBlob 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyRoundTripBlob(ctx context.Context, arg1 OwnedBlob) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCRoundTripBlobMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripBlobRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCRoundTripBlobMethodID, request)
}

// BroadcastRoundTripBlob 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastRoundTripBlob(ctx context.Context, arg1 OwnedBlob) error {
	request, err := encodePlayerRPCRoundTripBlobRequest(client.client, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCRoundTripBlobMethodID, request)
}

// encodePlayerRPCRoundTripPackedIDRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCRoundTripPackedIDRequest(client rpc.Client, kind rpc.CallKind, arg1 PackedPlayerID) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := PackedPlayerIDCodec{}.Size(&(arg1))
	if customErr2 != nil {
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	customSize3, customErr4 := PackedPlayerIDCodec{}.Size(&(arg1))
	if customErr4 != nil {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	customPayload5, reserveErr6 := writer.ReserveCustom(customSize3)
	if reserveErr6 != nil {
		buffer.Release()
		return nil, reserveErr6
	}
	customWritten7, customErr8 := PackedPlayerIDCodec{}.MarshalTo(customPayload5, &(arg1))
	if customErr8 != nil || customWritten7 != len(customPayload5) {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCRoundTripPackedIDRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripPackedIDRequest(data []byte) (arg1 PackedPlayerID, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := PackedPlayerIDCodec{}.Unmarshal(customPayload1, &(arg1))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCRoundTripPackedIDResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCRoundTripPackedIDResponse(response *rpc.ResponseWriter, result1 PackedPlayerID) error {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := PackedPlayerIDCodec{}.Size(&(result1))
	if customErr2 != nil {
		return errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	customSize3, customErr4 := PackedPlayerIDCodec{}.Size(&(result1))
	if customErr4 != nil {
		return errs.ErrRPCEncodeFailed
	}
	customPayload5, reserveErr6 := writer.ReserveCustom(customSize3)
	if reserveErr6 != nil {
		return reserveErr6
	}
	customWritten7, customErr8 := PackedPlayerIDCodec{}.MarshalTo(customPayload5, &(result1))
	if customErr8 != nil || customWritten7 != len(customPayload5) {
		return errs.ErrRPCEncodeFailed
	}
	return writer.Done()
}

// decodePlayerRPCRoundTripPackedIDResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripPackedIDResponse(data []byte) (result1 PackedPlayerID, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := PackedPlayerIDCodec{}.Unmarshal(customPayload1, &(result1))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	decodeErr = reader.Done()
	return
}

// AwaitRoundTripPackedID 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitRoundTripPackedID(ctx context.Context, arg1 PackedPlayerID) (result1 PackedPlayerID, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCRoundTripPackedIDMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCRoundTripPackedIDRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCRoundTripPackedIDMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCRoundTripPackedIDResponse(data)
		return err
	})
	return
}

// AsyncRoundTripPackedID 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncRoundTripPackedID(ctx context.Context, arg1 PackedPlayerID, callback func(context.Context, PackedPlayerID, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCRoundTripPackedIDMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripPackedIDRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCRoundTripPackedIDMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(PackedPlayerID), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCRoundTripPackedIDResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyRoundTripPackedID 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyRoundTripPackedID(ctx context.Context, arg1 PackedPlayerID) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCRoundTripPackedIDMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripPackedIDRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCRoundTripPackedIDMethodID, request)
}

// BroadcastRoundTripPackedID 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastRoundTripPackedID(ctx context.Context, arg1 PackedPlayerID) error {
	request, err := encodePlayerRPCRoundTripPackedIDRequest(client.client, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCRoundTripPackedIDMethodID, request)
}

// encodePlayerRPCRoundTripTimeRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCRoundTripTimeRequest(client rpc.Client, kind rpc.CallKind, arg1 TimeEnvelope, arg2 int) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := TimeCodec{}.Size(&(arg1.At))
	if customErr2 != nil {
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg1.Optional != nil {
		customSize3, customErr4 := TimeCodec{}.Size(&(*arg1.Optional))
		if customErr4 != nil {
			return nil, errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize3); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.History), arg1.History == nil); err != nil {
		return nil, err
	}
	for index5 := range arg1.History {
		customSize6, customErr7 := TimeCodec{}.Size(&(arg1.History[index5]))
		if customErr7 != nil {
			return nil, errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize6); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.ByTime), arg1.ByTime == nil); err != nil {
		return nil, err
	}
	for key8, value9 := range arg1.ByTime {
		customSize10, customErr11 := TimeCodec{}.Size(&(key8))
		if customErr11 != nil {
			return nil, errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize10); err != nil {
			return nil, err
		}
		customSize12, customErr13 := TimeCodec{}.Size(&(value9))
		if customErr13 != nil {
			return nil, errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize12); err != nil {
			return nil, err
		}
	}
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	customSize14, customErr15 := TimeCodec{}.Size(&(arg1.At))
	if customErr15 != nil {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	customPayload16, reserveErr17 := writer.ReserveCustom(customSize14)
	if reserveErr17 != nil {
		buffer.Release()
		return nil, reserveErr17
	}
	customWritten18, customErr19 := TimeCodec{}.MarshalTo(customPayload16, &(arg1.At))
	if customErr19 != nil || customWritten18 != len(customPayload16) {
		buffer.Release()
		return nil, errs.ErrRPCEncodeFailed
	}
	if err := writer.WritePresence(arg1.Optional != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg1.Optional != nil {
		customSize20, customErr21 := TimeCodec{}.Size(&(*arg1.Optional))
		if customErr21 != nil {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
		customPayload22, reserveErr23 := writer.ReserveCustom(customSize20)
		if reserveErr23 != nil {
			buffer.Release()
			return nil, reserveErr23
		}
		customWritten24, customErr25 := TimeCodec{}.MarshalTo(customPayload22, &(*arg1.Optional))
		if customErr25 != nil || customWritten24 != len(customPayload22) {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
	}
	if err := writer.WriteContainer(len(arg1.History), arg1.History == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index26 := range arg1.History {
		customSize27, customErr28 := TimeCodec{}.Size(&(arg1.History[index26]))
		if customErr28 != nil {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
		customPayload29, reserveErr30 := writer.ReserveCustom(customSize27)
		if reserveErr30 != nil {
			buffer.Release()
			return nil, reserveErr30
		}
		customWritten31, customErr32 := TimeCodec{}.MarshalTo(customPayload29, &(arg1.History[index26]))
		if customErr32 != nil || customWritten31 != len(customPayload29) {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
	}
	if err := writer.WriteContainer(len(arg1.ByTime), arg1.ByTime == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for key33, value34 := range arg1.ByTime {
		customSize35, customErr36 := TimeCodec{}.Size(&(key33))
		if customErr36 != nil {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
		customPayload37, reserveErr38 := writer.ReserveCustom(customSize35)
		if reserveErr38 != nil {
			buffer.Release()
			return nil, reserveErr38
		}
		customWritten39, customErr40 := TimeCodec{}.MarshalTo(customPayload37, &(key33))
		if customErr40 != nil || customWritten39 != len(customPayload37) {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
		customSize41, customErr42 := TimeCodec{}.Size(&(value34))
		if customErr42 != nil {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
		customPayload43, reserveErr44 := writer.ReserveCustom(customSize41)
		if reserveErr44 != nil {
			buffer.Release()
			return nil, reserveErr44
		}
		customWritten45, customErr46 := TimeCodec{}.MarshalTo(customPayload43, &(value34))
		if customErr46 != nil || customWritten45 != len(customPayload43) {
			buffer.Release()
			return nil, errs.ErrRPCEncodeFailed
		}
	}
	if err := writer.WriteInt(int(arg2)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCRoundTripTimeRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripTimeRequest(data []byte) (arg1 TimeEnvelope, arg2 int, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := TimeCodec{}.Unmarshal(customPayload1, &(arg1.At))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		arg1.Optional = (*time.Time)(new(time.Time))
		var customPayload4 []byte
		customPayload4, decodeErr = reader.ReadCustomPayload()
		if decodeErr != nil {
			return
		}
		customErr5 := TimeCodec{}.Unmarshal(customPayload4, &(*arg1.Optional))
		if customErr5 != nil {
			decodeErr = reader.Reject()
			return
		}
	}
	var length6 int
	var isNil7 bool
	length6, isNil7, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length6, 4)
	if decodeErr != nil {
		return
	}
	if !isNil7 {
		arg1.History = make([]time.Time, length6)
		for index8 := 0; index8 < length6; index8++ {
			var customPayload9 []byte
			customPayload9, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr10 := TimeCodec{}.Unmarshal(customPayload9, &(arg1.History[index8]))
			if customErr10 != nil {
				decodeErr = reader.Reject()
				return
			}
		}
	}
	var length11 int
	var isNil12 bool
	length11, isNil12, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length11, 8)
	if decodeErr != nil {
		return
	}
	if !isNil12 {
		arg1.ByTime = make(map[time.Time]time.Time, length11)
		for index13 := 0; index13 < length11; index13++ {
			var key14 time.Time
			var value15 time.Time
			var customPayload16 []byte
			customPayload16, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr17 := TimeCodec{}.Unmarshal(customPayload16, &(key14))
			if customErr17 != nil {
				decodeErr = reader.Reject()
				return
			}
			var customPayload18 []byte
			customPayload18, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr19 := TimeCodec{}.Unmarshal(customPayload18, &(value15))
			if customErr19 != nil {
				decodeErr = reader.Reject()
				return
			}
			arg1.ByTime[key14] = value15
		}
	}
	var decoded20 int
	decoded20, decodeErr = reader.ReadInt()
	if decodeErr != nil {
		return
	}
	arg2 = int(decoded20)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCRoundTripTimeResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCRoundTripTimeResponse(response *rpc.ResponseWriter, result1 TimeEnvelope) error {
	sizer := rpc.NewSizer()
	customSize1, customErr2 := TimeCodec{}.Size(&(result1.At))
	if customErr2 != nil {
		return errs.ErrRPCEncodeFailed
	}
	if err := sizer.AddCustom(customSize1); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if result1.Optional != nil {
		customSize3, customErr4 := TimeCodec{}.Size(&(*result1.Optional))
		if customErr4 != nil {
			return errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize3); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.History), result1.History == nil); err != nil {
		return err
	}
	for index5 := range result1.History {
		customSize6, customErr7 := TimeCodec{}.Size(&(result1.History[index5]))
		if customErr7 != nil {
			return errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize6); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.ByTime), result1.ByTime == nil); err != nil {
		return err
	}
	for key8, value9 := range result1.ByTime {
		customSize10, customErr11 := TimeCodec{}.Size(&(key8))
		if customErr11 != nil {
			return errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize10); err != nil {
			return err
		}
		customSize12, customErr13 := TimeCodec{}.Size(&(value9))
		if customErr13 != nil {
			return errs.ErrRPCEncodeFailed
		}
		if err := sizer.AddCustom(customSize12); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	customSize14, customErr15 := TimeCodec{}.Size(&(result1.At))
	if customErr15 != nil {
		return errs.ErrRPCEncodeFailed
	}
	customPayload16, reserveErr17 := writer.ReserveCustom(customSize14)
	if reserveErr17 != nil {
		return reserveErr17
	}
	customWritten18, customErr19 := TimeCodec{}.MarshalTo(customPayload16, &(result1.At))
	if customErr19 != nil || customWritten18 != len(customPayload16) {
		return errs.ErrRPCEncodeFailed
	}
	if err := writer.WritePresence(result1.Optional != nil); err != nil {
		return err
	}
	if result1.Optional != nil {
		customSize20, customErr21 := TimeCodec{}.Size(&(*result1.Optional))
		if customErr21 != nil {
			return errs.ErrRPCEncodeFailed
		}
		customPayload22, reserveErr23 := writer.ReserveCustom(customSize20)
		if reserveErr23 != nil {
			return reserveErr23
		}
		customWritten24, customErr25 := TimeCodec{}.MarshalTo(customPayload22, &(*result1.Optional))
		if customErr25 != nil || customWritten24 != len(customPayload22) {
			return errs.ErrRPCEncodeFailed
		}
	}
	if err := writer.WriteContainer(len(result1.History), result1.History == nil); err != nil {
		return err
	}
	for index26 := range result1.History {
		customSize27, customErr28 := TimeCodec{}.Size(&(result1.History[index26]))
		if customErr28 != nil {
			return errs.ErrRPCEncodeFailed
		}
		customPayload29, reserveErr30 := writer.ReserveCustom(customSize27)
		if reserveErr30 != nil {
			return reserveErr30
		}
		customWritten31, customErr32 := TimeCodec{}.MarshalTo(customPayload29, &(result1.History[index26]))
		if customErr32 != nil || customWritten31 != len(customPayload29) {
			return errs.ErrRPCEncodeFailed
		}
	}
	if err := writer.WriteContainer(len(result1.ByTime), result1.ByTime == nil); err != nil {
		return err
	}
	for key33, value34 := range result1.ByTime {
		customSize35, customErr36 := TimeCodec{}.Size(&(key33))
		if customErr36 != nil {
			return errs.ErrRPCEncodeFailed
		}
		customPayload37, reserveErr38 := writer.ReserveCustom(customSize35)
		if reserveErr38 != nil {
			return reserveErr38
		}
		customWritten39, customErr40 := TimeCodec{}.MarshalTo(customPayload37, &(key33))
		if customErr40 != nil || customWritten39 != len(customPayload37) {
			return errs.ErrRPCEncodeFailed
		}
		customSize41, customErr42 := TimeCodec{}.Size(&(value34))
		if customErr42 != nil {
			return errs.ErrRPCEncodeFailed
		}
		customPayload43, reserveErr44 := writer.ReserveCustom(customSize41)
		if reserveErr44 != nil {
			return reserveErr44
		}
		customWritten45, customErr46 := TimeCodec{}.MarshalTo(customPayload43, &(value34))
		if customErr46 != nil || customWritten45 != len(customPayload43) {
			return errs.ErrRPCEncodeFailed
		}
	}
	return writer.Done()
}

// decodePlayerRPCRoundTripTimeResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRoundTripTimeResponse(data []byte) (result1 TimeEnvelope, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var customPayload1 []byte
	customPayload1, decodeErr = reader.ReadCustomPayload()
	if decodeErr != nil {
		return
	}
	customErr2 := TimeCodec{}.Unmarshal(customPayload1, &(result1.At))
	if customErr2 != nil {
		decodeErr = reader.Reject()
		return
	}
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		result1.Optional = (*time.Time)(new(time.Time))
		var customPayload4 []byte
		customPayload4, decodeErr = reader.ReadCustomPayload()
		if decodeErr != nil {
			return
		}
		customErr5 := TimeCodec{}.Unmarshal(customPayload4, &(*result1.Optional))
		if customErr5 != nil {
			decodeErr = reader.Reject()
			return
		}
	}
	var length6 int
	var isNil7 bool
	length6, isNil7, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length6, 4)
	if decodeErr != nil {
		return
	}
	if !isNil7 {
		result1.History = make([]time.Time, length6)
		for index8 := 0; index8 < length6; index8++ {
			var customPayload9 []byte
			customPayload9, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr10 := TimeCodec{}.Unmarshal(customPayload9, &(result1.History[index8]))
			if customErr10 != nil {
				decodeErr = reader.Reject()
				return
			}
		}
	}
	var length11 int
	var isNil12 bool
	length11, isNil12, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length11, 8)
	if decodeErr != nil {
		return
	}
	if !isNil12 {
		result1.ByTime = make(map[time.Time]time.Time, length11)
		for index13 := 0; index13 < length11; index13++ {
			var key14 time.Time
			var value15 time.Time
			var customPayload16 []byte
			customPayload16, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr17 := TimeCodec{}.Unmarshal(customPayload16, &(key14))
			if customErr17 != nil {
				decodeErr = reader.Reject()
				return
			}
			var customPayload18 []byte
			customPayload18, decodeErr = reader.ReadCustomPayload()
			if decodeErr != nil {
				return
			}
			customErr19 := TimeCodec{}.Unmarshal(customPayload18, &(value15))
			if customErr19 != nil {
				decodeErr = reader.Reject()
				return
			}
			result1.ByTime[key14] = value15
		}
	}
	decodeErr = reader.Done()
	return
}

// AwaitRoundTripTime 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitRoundTripTime(ctx context.Context, arg1 TimeEnvelope, arg2 int) (result1 TimeEnvelope, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCRoundTripTimeMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCRoundTripTimeRequest(preparedClient, rpc.CallRequest, arg1, arg2)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCRoundTripTimeMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCRoundTripTimeResponse(data)
		return err
	})
	return
}

// AsyncRoundTripTime 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncRoundTripTime(ctx context.Context, arg1 TimeEnvelope, arg2 int, callback func(context.Context, TimeEnvelope, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCRoundTripTimeMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripTimeRequest(preparedClient, rpc.CallRequest, arg1, arg2)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCRoundTripTimeMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(TimeEnvelope), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCRoundTripTimeResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyRoundTripTime 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyRoundTripTime(ctx context.Context, arg1 TimeEnvelope, arg2 int) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCRoundTripTimeMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRoundTripTimeRequest(preparedClient, rpc.CallNotify, arg1, arg2)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCRoundTripTimeMethodID, request)
}

// BroadcastRoundTripTime 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastRoundTripTime(ctx context.Context, arg1 TimeEnvelope, arg2 int) error {
	request, err := encodePlayerRPCRoundTripTimeRequest(client.client, rpc.CallNotify, arg1, arg2)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCRoundTripTimeMethodID, request)
}

// encodePlayerRPCSavePlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCSavePlayerRequest(client rpc.Client, kind rpc.CallKind, arg1 PlayerData) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg1.Name)); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg1.Score != nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.Tags), arg1.Tags == nil); err != nil {
		return nil, err
	}
	for index1 := range arg1.Tags {
		if err := sizer.AddString(string(arg1.Tags[index1])); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.Metadata), arg1.Metadata == nil); err != nil {
		return nil, err
	}
	for key2, value3 := range arg1.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return nil, err
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return nil, err
			}
		}
	}
	if err := sizer.AddBytes([]byte(arg1.Payload)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1.ID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg1.Name)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WritePresence(arg1.Score != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg1.Score != nil {
		if err := writer.WriteInt32(int32((*arg1.Score))); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg1.Tags), arg1.Tags == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index4 := range arg1.Tags {
		if err := writer.WriteString(string(arg1.Tags[index4])); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg1.Metadata), arg1.Metadata == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for key5, value6 := range arg1.Metadata {
		if err := writer.WriteString(string(key5)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WritePresence(value6 != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if value6 != nil {
			if err := writer.WriteString(string((*value6).Value)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.WriteBytes([]byte(arg1.Payload)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCSavePlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCSavePlayerRequest(data []byte) (arg1 PlayerData, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1.ID = int64(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.Name = string(decoded2)
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		arg1.Score = (OptionalScore)(new(int32))
		var decoded4 int32
		decoded4, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*arg1.Score) = int32(decoded4)
	}
	var length5 int
	var isNil6 bool
	length5, isNil6, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length5, 4)
	if decodeErr != nil {
		return
	}
	if !isNil6 {
		arg1.Tags = make([]string, length5)
		for index7 := 0; index7 < length5; index7++ {
			var decoded8 string
			decoded8, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg1.Tags[index7] = string(decoded8)
		}
	}
	var length9 int
	var isNil10 bool
	length9, isNil10, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length9, 5)
	if decodeErr != nil {
		return
	}
	if !isNil10 {
		arg1.Metadata = make(map[string]*wrapperspb.StringValue, length9)
		for index11 := 0; index11 < length9; index11++ {
			var key12 string
			var value13 *wrapperspb.StringValue
			var decoded14 string
			decoded14, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key12 = string(decoded14)
			var present15 bool
			present15, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present15 {
				value13 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded16 string
				decoded16, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value13).Value = string(decoded16)
			}
			arg1.Metadata[key12] = value13
		}
	}
	var decoded17 []byte
	decoded17, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg1.Payload = []byte(decoded17)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCSavePlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCSavePlayerResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodePlayerRPCSavePlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCSavePlayerResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitSavePlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitSavePlayer(ctx context.Context, arg1 PlayerData) (err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCSavePlayerMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCSavePlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCSavePlayerMethodID, request, func(data []byte) error {
		return decodePlayerRPCSavePlayerResponse(data)
	})
	return
}

// AsyncSavePlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncSavePlayer(ctx context.Context, arg1 PlayerData, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCSavePlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCSavePlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCSavePlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodePlayerRPCSavePlayerResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifySavePlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifySavePlayer(ctx context.Context, arg1 PlayerData) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCSavePlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCSavePlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCSavePlayerMethodID, request)
}

// BroadcastSavePlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastSavePlayer(ctx context.Context, arg1 PlayerData) error {
	request, err := encodePlayerRPCSavePlayerRequest(client.client, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCSavePlayerMethodID, request)
}

// playerRPCDispatcher 把 MethodID 静态分派到 PlayerRPC 实现。
type playerRPCDispatcher struct{ impl PlayerRPC }

// NewPlayerRPCDispatcher 创建不使用反射的静态 Dispatcher。
func NewPlayerRPCDispatcher(impl PlayerRPC) rpc.Dispatcher {
	return &playerRPCDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *playerRPCDispatcher) ContractID() rpc.ContractID { return playerRPCContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *playerRPCDispatcher) Fingerprint() rpc.ContractFingerprint {
	return playerRPCFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *playerRPCDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case playerRPCEchoNameMethodID:
		arg1, err := decodePlayerRPCEchoNameRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.EchoName(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1 := dispatcher.impl.EchoName(ctx, arg1)
		if err := encodePlayerRPCEchoNameResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCGetPlayerMethodID:
		arg1, arg2, arg3, err := decodePlayerRPCGetPlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, _, callErr := dispatcher.impl.GetPlayer(ctx, arg1, arg2, arg3)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, result2, callErr := dispatcher.impl.GetPlayer(ctx, arg1, arg2, arg3)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCGetPlayerResponse(&response, result1, result2); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCPlayerOnlineMethodID:
		arg1, err := decodePlayerRPCPlayerOnlineRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.PlayerOnline(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		return response, errs.ErrInvalidArgument
	case playerRPCRoundTripBlobMethodID:
		arg1, err := decodePlayerRPCRoundTripBlobRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.RoundTripBlob(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1 := dispatcher.impl.RoundTripBlob(ctx, arg1)
		if err := encodePlayerRPCRoundTripBlobResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCRoundTripPackedIDMethodID:
		arg1, err := decodePlayerRPCRoundTripPackedIDRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.RoundTripPackedID(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1 := dispatcher.impl.RoundTripPackedID(ctx, arg1)
		if err := encodePlayerRPCRoundTripPackedIDResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCRoundTripTimeMethodID:
		arg1, arg2, err := decodePlayerRPCRoundTripTimeRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.RoundTripTime(ctx, arg1, arg2)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.RoundTripTime(ctx, arg1, arg2)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCRoundTripTimeResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCSavePlayerMethodID:
		arg1, err := decodePlayerRPCSavePlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.SavePlayer(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.SavePlayer(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCSavePlayerResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

// RPCDispatcher 由 origingen 生成，使 Node 无需业务注册样板即可发现 github.com/duanhf2012/origin/v3/tests/integration/rpcfixture.PlayerRPC。
func (service *PlayerService) RPCDispatcher() rpc.Dispatcher {
	return NewPlayerRPCDispatcher(service)
}
