// Code generated by origingen rpc; DO NOT EDIT.

package rpcfixture

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	_ uint = rpc.GeneratedABIVersion - 1
	_ uint = 1 - rpc.GeneratedABIVersion
)

const playerRPCContractID rpc.ContractID = 0xb3ca21d38db4b2fc

var playerRPCFingerprint = rpc.ContractFingerprint{0x4b, 0x53, 0x82, 0x35, 0xbd, 0x64, 0x38, 0xc8, 0x06, 0x3d, 0x04, 0x8a, 0x12, 0x0b, 0x81, 0x14, 0xb5, 0x4b, 0x39, 0x8b, 0x7f, 0xab, 0xe1, 0xd6, 0xfa, 0xd5, 0x34, 0x10, 0xfb, 0x25, 0xeb, 0xf8}

const playerRPCEchoNameMethodID rpc.MethodID = 0xb441ccb1960cd3b9
const playerRPCGetPlayerMethodID rpc.MethodID = 0x0612b3cda06ad14b
const playerRPCPlayerOnlineMethodID rpc.MethodID = 0xafc4908eabe03c37
const playerRPCSavePlayerMethodID rpc.MethodID = 0x5f67ae07657409b1

// PlayerRPCClient 是 github.com/duanhf2012/origin/v3/tests/integration/rpcfixture.PlayerRPC 的强类型生成客户端。
type PlayerRPCClient struct {
	client rpc.Client
}

// NewPlayerRPCClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewPlayerRPCClient(owner service.IService, target rpc.Target) PlayerRPCClient {
	return PlayerRPCClient{client: rpc.NewGeneratedClient(owner, target, playerRPCContractID, playerRPCFingerprint)}
}

// encodePlayerRPCEchoNameRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCEchoNameRequest(client rpc.Client, arg1 string) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCEchoNameRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCEchoNameRequest(data []byte) (arg1 string, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCEchoNameResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCEchoNameResponse(response *rpc.ResponseWriter, result1 string) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1)); err != nil {
		return err
	}
	return writer.Done()
}

// decodePlayerRPCEchoNameResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCEchoNameResponse(data []byte) (result1 string, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// AwaitEchoName 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitEchoName(ctx context.Context, arg1 string) (result1 string, err error) {
	request, err := encodePlayerRPCEchoNameRequest(client.client, arg1)
	if err != nil {
		return
	}
	err = client.client.Await(ctx, playerRPCEchoNameMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCEchoNameResponse(data)
		return err
	})
	return
}

// AsyncEchoName 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncEchoName(ctx context.Context, arg1 string, callback func(context.Context, string, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	request, err := encodePlayerRPCEchoNameRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Async(ctx, playerRPCEchoNameMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(string), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCEchoNameResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyEchoName 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyEchoName(ctx context.Context, arg1 string) error {
	request, err := encodePlayerRPCEchoNameRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Notify(ctx, playerRPCEchoNameMethodID, request)
}

// BroadcastEchoName 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastEchoName(ctx context.Context, arg1 string) error {
	request, err := encodePlayerRPCEchoNameRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCEchoNameMethodID, request)
}

// encodePlayerRPCGetPlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCGetPlayerRequest(client rpc.Client, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg2.Name)); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg2.Score != nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg2.Tags), arg2.Tags == nil); err != nil {
		return nil, err
	}
	for index1 := range arg2.Tags {
		if err := sizer.AddString(string(arg2.Tags[index1])); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg2.Metadata), arg2.Metadata == nil); err != nil {
		return nil, err
	}
	for key2, value3 := range arg2.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return nil, err
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return nil, err
			}
		}
	}
	if err := sizer.AddBytes([]byte(arg2.Payload)); err != nil {
		return nil, err
	}
	if arg3 == nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	} else {
		if err := sizer.AddProto(arg3); err != nil {
			return nil, err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt64(int64(arg2.ID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg2.Name)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WritePresence(arg2.Score != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg2.Score != nil {
		if err := writer.WriteInt32(int32((*arg2.Score))); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg2.Tags), arg2.Tags == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index1 := range arg2.Tags {
		if err := writer.WriteString(string(arg2.Tags[index1])); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg2.Metadata), arg2.Metadata == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for key2, value3 := range arg2.Metadata {
		if err := writer.WriteString(string(key2)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WritePresence(value3 != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if value3 != nil {
			if err := writer.WriteString(string((*value3).Value)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.WriteBytes([]byte(arg2.Payload)); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg3 == nil {
		if err := writer.WriteNil(); err != nil {
			buffer.Release()
			return nil, err
		}
	} else {
		if err := writer.WriteProto(arg3); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCGetPlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerRequest(data []byte) (arg1 int64, arg2 PlayerData, arg3 *structpb.Struct, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	var decoded2 int64
	decoded2, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg2.ID = int64(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg2.Name = string(decoded3)
	var present4 bool
	present4, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present4 {
		arg2.Score = (OptionalScore)(new(int32))
		var decoded5 int32
		decoded5, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*arg2.Score) = int32(decoded5)
	}
	var length6 int
	var isNil7 bool
	length6, isNil7, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length6, 4)
	if decodeErr != nil {
		return
	}
	if !isNil7 {
		arg2.Tags = make([]string, length6)
		for index8 := 0; index8 < length6; index8++ {
			var decoded9 string
			decoded9, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg2.Tags[index8] = string(decoded9)
		}
	}
	var length10 int
	var isNil11 bool
	length10, isNil11, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length10, 5)
	if decodeErr != nil {
		return
	}
	if !isNil11 {
		arg2.Metadata = make(map[string]*wrapperspb.StringValue, length10)
		for index12 := 0; index12 < length10; index12++ {
			var key13 string
			var value14 *wrapperspb.StringValue
			var decoded15 string
			decoded15, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key13 = string(decoded15)
			var present16 bool
			present16, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present16 {
				value14 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded17 string
				decoded17, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value14).Value = string(decoded17)
			}
			arg2.Metadata[key13] = value14
		}
	}
	var decoded18 []byte
	decoded18, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg2.Payload = []byte(decoded18)
	var payload19 []byte
	var isNil20 bool
	payload19, isNil20, decodeErr = reader.ReadProtoPayload()
	if decodeErr != nil {
		return
	}
	if !isNil20 {
		arg3 = new(structpb.Struct)
		decodeErr = rpc.UnmarshalProto(payload19, arg3, false)
		if decodeErr != nil {
			return
		}
	}
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCGetPlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCGetPlayerResponse(response *rpc.ResponseWriter, result1 PlayerData, result2 *structpb.Struct) error {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.Name)); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if result1.Score != nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.Tags), result1.Tags == nil); err != nil {
		return err
	}
	for index1 := range result1.Tags {
		if err := sizer.AddString(string(result1.Tags[index1])); err != nil {
			return err
		}
	}
	if err := sizer.AddContainer(len(result1.Metadata), result1.Metadata == nil); err != nil {
		return err
	}
	for key2, value3 := range result1.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return err
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return err
			}
		}
	}
	if err := sizer.AddBytes([]byte(result1.Payload)); err != nil {
		return err
	}
	if result2 == nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
	} else {
		if err := sizer.AddProto(result2); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteInt64(int64(result1.ID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.Name)); err != nil {
		return err
	}
	if err := writer.WritePresence(result1.Score != nil); err != nil {
		return err
	}
	if result1.Score != nil {
		if err := writer.WriteInt32(int32((*result1.Score))); err != nil {
			return err
		}
	}
	if err := writer.WriteContainer(len(result1.Tags), result1.Tags == nil); err != nil {
		return err
	}
	for index1 := range result1.Tags {
		if err := writer.WriteString(string(result1.Tags[index1])); err != nil {
			return err
		}
	}
	if err := writer.WriteContainer(len(result1.Metadata), result1.Metadata == nil); err != nil {
		return err
	}
	for key2, value3 := range result1.Metadata {
		if err := writer.WriteString(string(key2)); err != nil {
			return err
		}
		if err := writer.WritePresence(value3 != nil); err != nil {
			return err
		}
		if value3 != nil {
			if err := writer.WriteString(string((*value3).Value)); err != nil {
				return err
			}
		}
	}
	if err := writer.WriteBytes([]byte(result1.Payload)); err != nil {
		return err
	}
	if result2 == nil {
		if err := writer.WriteNil(); err != nil {
			return err
		}
	} else {
		if err := writer.WriteProto(result2); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodePlayerRPCGetPlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerResponse(data []byte) (result1 PlayerData, result2 *structpb.Struct, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.ID = int64(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.Name = string(decoded2)
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		result1.Score = (OptionalScore)(new(int32))
		var decoded4 int32
		decoded4, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Score) = int32(decoded4)
	}
	var length5 int
	var isNil6 bool
	length5, isNil6, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length5, 4)
	if decodeErr != nil {
		return
	}
	if !isNil6 {
		result1.Tags = make([]string, length5)
		for index7 := 0; index7 < length5; index7++ {
			var decoded8 string
			decoded8, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			result1.Tags[index7] = string(decoded8)
		}
	}
	var length9 int
	var isNil10 bool
	length9, isNil10, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length9, 5)
	if decodeErr != nil {
		return
	}
	if !isNil10 {
		result1.Metadata = make(map[string]*wrapperspb.StringValue, length9)
		for index11 := 0; index11 < length9; index11++ {
			var key12 string
			var value13 *wrapperspb.StringValue
			var decoded14 string
			decoded14, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key12 = string(decoded14)
			var present15 bool
			present15, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present15 {
				value13 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded16 string
				decoded16, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value13).Value = string(decoded16)
			}
			result1.Metadata[key12] = value13
		}
	}
	var decoded17 []byte
	decoded17, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	result1.Payload = []byte(decoded17)
	var payload18 []byte
	var isNil19 bool
	payload18, isNil19, decodeErr = reader.ReadProtoPayload()
	if decodeErr != nil {
		return
	}
	if !isNil19 {
		result2 = new(structpb.Struct)
		decodeErr = rpc.UnmarshalProto(payload18, result2, true)
		if decodeErr != nil {
			return
		}
	}
	decodeErr = reader.Done()
	return
}

// AwaitGetPlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) (result1 PlayerData, result2 *structpb.Struct, err error) {
	request, err := encodePlayerRPCGetPlayerRequest(client.client, arg1, arg2, arg3)
	if err != nil {
		return
	}
	err = client.client.Await(ctx, playerRPCGetPlayerMethodID, request, func(data []byte) error {
		result1, result2, err = decodePlayerRPCGetPlayerResponse(data)
		return err
	})
	return
}

// AsyncGetPlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct, callback func(context.Context, PlayerData, *structpb.Struct, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	request, err := encodePlayerRPCGetPlayerRequest(client.client, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return client.client.Async(ctx, playerRPCGetPlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(PlayerData), *new(*structpb.Struct), callErr)
			return
		}
		result1, result2, decodeErr := decodePlayerRPCGetPlayerResponse(data)
		callback(callbackCtx, result1, result2, decodeErr)
	})
}

// NotifyGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) error {
	request, err := encodePlayerRPCGetPlayerRequest(client.client, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return client.client.Notify(ctx, playerRPCGetPlayerMethodID, request)
}

// BroadcastGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastGetPlayer(ctx context.Context, arg1 int64, arg2 PlayerData, arg3 *structpb.Struct) error {
	request, err := encodePlayerRPCGetPlayerRequest(client.client, arg1, arg2, arg3)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCGetPlayerMethodID, request)
}

// encodePlayerRPCPlayerOnlineRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCPlayerOnlineRequest(client rpc.Client, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCPlayerOnlineRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCPlayerOnlineRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// NotifyPlayerOnline 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyPlayerOnline(ctx context.Context, arg1 int64) error {
	request, err := encodePlayerRPCPlayerOnlineRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Notify(ctx, playerRPCPlayerOnlineMethodID, request)
}

// BroadcastPlayerOnline 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastPlayerOnline(ctx context.Context, arg1 int64) error {
	request, err := encodePlayerRPCPlayerOnlineRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCPlayerOnlineMethodID, request)
}

// encodePlayerRPCSavePlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCSavePlayerRequest(client rpc.Client, arg1 PlayerData) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg1.Name)); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg1.Score != nil {
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.Tags), arg1.Tags == nil); err != nil {
		return nil, err
	}
	for index1 := range arg1.Tags {
		if err := sizer.AddString(string(arg1.Tags[index1])); err != nil {
			return nil, err
		}
	}
	if err := sizer.AddContainer(len(arg1.Metadata), arg1.Metadata == nil); err != nil {
		return nil, err
	}
	for key2, value3 := range arg1.Metadata {
		if err := sizer.AddString(string(key2)); err != nil {
			return nil, err
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if value3 != nil {
			if err := sizer.AddString(string((*value3).Value)); err != nil {
				return nil, err
			}
		}
	}
	if err := sizer.AddBytes([]byte(arg1.Payload)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1.ID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg1.Name)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WritePresence(arg1.Score != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg1.Score != nil {
		if err := writer.WriteInt32(int32((*arg1.Score))); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg1.Tags), arg1.Tags == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index1 := range arg1.Tags {
		if err := writer.WriteString(string(arg1.Tags[index1])); err != nil {
			buffer.Release()
			return nil, err
		}
	}
	if err := writer.WriteContainer(len(arg1.Metadata), arg1.Metadata == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for key2, value3 := range arg1.Metadata {
		if err := writer.WriteString(string(key2)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WritePresence(value3 != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if value3 != nil {
			if err := writer.WriteString(string((*value3).Value)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.WriteBytes([]byte(arg1.Payload)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCSavePlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCSavePlayerRequest(data []byte) (arg1 PlayerData, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1.ID = int64(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.Name = string(decoded2)
	var present3 bool
	present3, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present3 {
		arg1.Score = (OptionalScore)(new(int32))
		var decoded4 int32
		decoded4, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*arg1.Score) = int32(decoded4)
	}
	var length5 int
	var isNil6 bool
	length5, isNil6, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length5, 4)
	if decodeErr != nil {
		return
	}
	if !isNil6 {
		arg1.Tags = make([]string, length5)
		for index7 := 0; index7 < length5; index7++ {
			var decoded8 string
			decoded8, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg1.Tags[index7] = string(decoded8)
		}
	}
	var length9 int
	var isNil10 bool
	length9, isNil10, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length9, 5)
	if decodeErr != nil {
		return
	}
	if !isNil10 {
		arg1.Metadata = make(map[string]*wrapperspb.StringValue, length9)
		for index11 := 0; index11 < length9; index11++ {
			var key12 string
			var value13 *wrapperspb.StringValue
			var decoded14 string
			decoded14, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			key12 = string(decoded14)
			var present15 bool
			present15, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present15 {
				value13 = (*wrapperspb.StringValue)(new(wrapperspb.StringValue))
				var decoded16 string
				decoded16, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*value13).Value = string(decoded16)
			}
			arg1.Metadata[key12] = value13
		}
	}
	var decoded17 []byte
	decoded17, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg1.Payload = []byte(decoded17)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCSavePlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCSavePlayerResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodePlayerRPCSavePlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCSavePlayerResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitSavePlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitSavePlayer(ctx context.Context, arg1 PlayerData) (err error) {
	request, err := encodePlayerRPCSavePlayerRequest(client.client, arg1)
	if err != nil {
		return
	}
	err = client.client.Await(ctx, playerRPCSavePlayerMethodID, request, func(data []byte) error {
		return decodePlayerRPCSavePlayerResponse(data)
	})
	return
}

// AsyncSavePlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncSavePlayer(ctx context.Context, arg1 PlayerData, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	request, err := encodePlayerRPCSavePlayerRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Async(ctx, playerRPCSavePlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodePlayerRPCSavePlayerResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifySavePlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifySavePlayer(ctx context.Context, arg1 PlayerData) error {
	request, err := encodePlayerRPCSavePlayerRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Notify(ctx, playerRPCSavePlayerMethodID, request)
}

// BroadcastSavePlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastSavePlayer(ctx context.Context, arg1 PlayerData) error {
	request, err := encodePlayerRPCSavePlayerRequest(client.client, arg1)
	if err != nil {
		return err
	}
	return client.client.Broadcast(ctx, playerRPCSavePlayerMethodID, request)
}

// playerRPCDispatcher 把 MethodID 静态分派到 PlayerRPC 实现。
type playerRPCDispatcher struct{ impl PlayerRPC }

// NewPlayerRPCDispatcher 创建不使用反射的静态 Dispatcher。
func NewPlayerRPCDispatcher(impl PlayerRPC) rpc.Dispatcher {
	return &playerRPCDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *playerRPCDispatcher) ContractID() rpc.ContractID { return playerRPCContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *playerRPCDispatcher) Fingerprint() rpc.ContractFingerprint {
	return playerRPCFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *playerRPCDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case playerRPCEchoNameMethodID:
		arg1, err := decodePlayerRPCEchoNameRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.EchoName(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1 := dispatcher.impl.EchoName(ctx, arg1)
		if err := encodePlayerRPCEchoNameResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCGetPlayerMethodID:
		arg1, arg2, arg3, err := decodePlayerRPCGetPlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, _, callErr := dispatcher.impl.GetPlayer(ctx, arg1, arg2, arg3)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, result2, callErr := dispatcher.impl.GetPlayer(ctx, arg1, arg2, arg3)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCGetPlayerResponse(&response, result1, result2); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCPlayerOnlineMethodID:
		arg1, err := decodePlayerRPCPlayerOnlineRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.PlayerOnline(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		return response, errs.ErrInvalidArgument
	case playerRPCSavePlayerMethodID:
		arg1, err := decodePlayerRPCSavePlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.SavePlayer(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.SavePlayer(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCSavePlayerResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

// RPCDispatcher 由 origingen 生成，使 Node 无需业务注册样板即可发现 github.com/duanhf2012/origin/v3/tests/integration/rpcfixture.PlayerRPC。
func (service *PlayerService) RPCDispatcher() rpc.Dispatcher {
	return NewPlayerRPCDispatcher(service)
}
