log:
  console: {enabled: true, level: info, format: text}
discovery:
  type: etcd
  etcd:
    endpoints: [http://127.0.0.1:2379]
    # 当前配置下启动的所有 Node 都注册到该网络，
    # 并自动能发现该网络中的所有服务。
    local_network: game-partition-1
    ttl: 5s
    request_timeout: 3s
nodes:
  - id: battle-room-1
    # 给当前 Node 发布的服务记录添加游戏类型标签。
    labels: {game_type: battle}
    services: [Service]
  - id: card-room-1
    labels: {game_type: card}
    services: [Service]
