log:
  console: {enabled: true, level: info, format: text}

discovery:
  type: origin
  origin:
    ttl: 5s
    server:
      node: discovery-1
      listen: 127.0.0.1:18081
      address: 127.0.0.1:18081

nodes:
  - id: discovery-1
    services: [DiscoveryService]
  - id: player-1
    rpc:
      transport: nats
      nats:
        namespace: origin-tutorial
        urls: [nats://127.0.0.1:4222]
    services: [PlayerService]
  - id: gateway-1
    rpc:
      transport: nats
      nats:
        namespace: origin-tutorial
        urls: [nats://127.0.0.1:4222]
    services: [GatewayService]
