// Code generated by origingen rpc; DO NOT EDIT.

package tutorialrpc

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const playerServiceContractID rpc.ContractID = 0x9beb0101e8c72617

var playerServiceFingerprint = rpc.ContractFingerprint{0x0f, 0x4e, 0xa5, 0x28, 0xa4, 0x39, 0x1c, 0xa8, 0x03, 0x60, 0x37, 0xd4, 0x51, 0x3b, 0xf3, 0xf8, 0xc4, 0xfc, 0xa6, 0xae, 0xa8, 0xc9, 0xa5, 0xef, 0xfe, 0x3c, 0x58, 0xe4, 0xe6, 0x9f, 0xc9, 0x90}

const playerServiceGetPlayerMethodID rpc.MethodID = 0xbb08d4402c86eb4b
const playerServiceRefreshMethodID rpc.MethodID = 0x109c1a32a01808f9

// PlayerServiceClient 是 github.com/duanhf2012/origin/v3/examples/_support/tutorialrpc.PlayerService 的强类型生成客户端。
type PlayerServiceClient struct {
	client rpc.Client
}

// NewPlayerServiceClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewPlayerServiceClient(owner service.IService, target rpc.Target) PlayerServiceClient {
	return PlayerServiceClient{client: rpc.NewGeneratedClient(owner, target, playerServiceContractID, playerServiceFingerprint)}
}

// BindPlayerService 使用契约默认 ServiceName "PlayerService" 绑定轻量客户端。
func BindPlayerService(owner service.IService) PlayerServiceClient {
	return NewPlayerServiceClient(owner, rpc.ToService("PlayerService"))
}

// BindPlayerServiceTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindPlayerServiceTo(owner service.IService, serviceName string) PlayerServiceClient {
	return NewPlayerServiceClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client PlayerServiceClient) OnNode(nodeID string) PlayerServiceClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// WhereLabels 派生按 Node Labels 精确筛选候选的客户端。
func (client PlayerServiceClient) WhereLabels(labels map[string]string) PlayerServiceClient {
	client.client = client.client.WhereLabels(labels)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client PlayerServiceClient) RouteRoundRobin() PlayerServiceClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client PlayerServiceClient) RouteRandom() PlayerServiceClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client PlayerServiceClient) Route(key any) PlayerServiceClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client PlayerServiceClient) RouteBy(selector rpc.RouteSelector) PlayerServiceClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client PlayerServiceClient) IncludeRetired() PlayerServiceClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodePlayerServiceGetPlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerServiceGetPlayerRequest(client rpc.Client, kind rpc.CallKind, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerServiceGetPlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerServiceGetPlayerRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// encodePlayerServiceGetPlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerServiceGetPlayerResponse(response *rpc.ResponseWriter, result1 string) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1)); err != nil {
		return err
	}
	return writer.Done()
}

// decodePlayerServiceGetPlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerServiceGetPlayerResponse(data []byte) (result1 string, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// AwaitGetPlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerServiceClient) AwaitGetPlayer(ctx context.Context, arg1 int64) (result1 string, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerServiceGetPlayerMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodePlayerServiceGetPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerServiceGetPlayerMethodID, request, func(data []byte) error {
		result1, err = decodePlayerServiceGetPlayerResponse(data)
		return err
	})
	return
}

// CallGetPlayer 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client PlayerServiceClient) CallGetPlayer(ctx context.Context, arg1 int64) (result1 string, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, playerServiceGetPlayerMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodePlayerServiceGetPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, playerServiceGetPlayerMethodID, request, func(data []byte) error {
		result1, err = decodePlayerServiceGetPlayerResponse(data)
		return err
	})
	return
}

// AsyncGetPlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerServiceClient) AsyncGetPlayer(ctx context.Context, arg1 int64, callback func(context.Context, string, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerServiceGetPlayerMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodePlayerServiceGetPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, playerServiceGetPlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(string), callErr)
			return
		}
		result1, decodeErr := decodePlayerServiceGetPlayerResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerServiceClient) NotifyGetPlayer(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerServiceGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerServiceGetPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerServiceGetPlayerMethodID, request)
}

// BroadcastGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerServiceClient) BroadcastGetPlayer(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, playerServiceGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerServiceGetPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, playerServiceGetPlayerMethodID, request)
}

// encodePlayerServiceRefreshRequest 计算并一次写入当前方法请求载荷。
func encodePlayerServiceRefreshRequest(client rpc.Client, kind rpc.CallKind, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerServiceRefreshRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerServiceRefreshRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// NotifyRefresh 提交通知并主动放弃业务结果。
func (client PlayerServiceClient) NotifyRefresh(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerServiceRefreshMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerServiceRefreshRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerServiceRefreshMethodID, request)
}

// BroadcastRefresh 提交通知并主动放弃业务结果。
func (client PlayerServiceClient) BroadcastRefresh(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, playerServiceRefreshMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerServiceRefreshRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, playerServiceRefreshMethodID, request)
}

// playerServiceDispatcher 把 MethodID 静态分派到 PlayerService 实现。
type playerServiceDispatcher struct{ impl PlayerService }

// NewPlayerServiceDispatcher 创建不使用反射的静态 Dispatcher。
func NewPlayerServiceDispatcher(impl PlayerService) rpc.Dispatcher {
	return &playerServiceDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *playerServiceDispatcher) ContractID() rpc.ContractID {
	return playerServiceContractID
}

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *playerServiceDispatcher) Fingerprint() rpc.ContractFingerprint {
	return playerServiceFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *playerServiceDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case playerServiceGetPlayerMethodID:
		arg1, err := decodePlayerServiceGetPlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.GetPlayer(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.GetPlayer(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerServiceGetPlayerResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerServiceRefreshMethodID:
		arg1, err := decodePlayerServiceRefreshRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.Refresh(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		return response, errs.ErrInvalidArgument
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

func init() {
	rpc.RegisterGeneratedContract(rpc.GeneratedContractDescriptor{
		ServiceName:  "PlayerService",
		ContractName: "github.com/duanhf2012/origin/v3/examples/_support/tutorialrpc.PlayerService",
		ContractID:   playerServiceContractID,
		Fingerprint:  playerServiceFingerprint,
		NewDispatcher: func(implementation any) (rpc.Dispatcher, bool) {
			target, ok := implementation.(PlayerService)
			if !ok {
				return nil, false
			}
			return NewPlayerServiceDispatcher(target), true
		},
	})
}
