// Code generated by origingen rpc; DO NOT EDIT.

package tutorialrpc

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const playerRPCContractID rpc.ContractID = 0xd45b085bf1fa7106

var playerRPCFingerprint = rpc.ContractFingerprint{0x6a, 0x2e, 0xb1, 0xb6, 0x43, 0xde, 0xf7, 0xfe, 0x83, 0xb1, 0x26, 0x8f, 0xf2, 0x15, 0x5b, 0xa6, 0xdc, 0x09, 0xc6, 0xf9, 0x9c, 0xc2, 0x62, 0x01, 0x4e, 0xa4, 0xdf, 0x21, 0xb1, 0xf8, 0xcc, 0x80}

const playerRPCGetPlayerMethodID rpc.MethodID = 0x88140c536b02355d
const playerRPCRefreshMethodID rpc.MethodID = 0x0b1fc7b7e7711bd1

// PlayerRPCClient 是 github.com/duanhf2012/origin/v3/examples/_support/tutorialrpc.PlayerRPC 的强类型生成客户端。
type PlayerRPCClient struct {
	client rpc.Client
}

// NewPlayerRPCClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewPlayerRPCClient(owner service.IService, target rpc.Target) PlayerRPCClient {
	return PlayerRPCClient{client: rpc.NewGeneratedClient(owner, target, playerRPCContractID, playerRPCFingerprint)}
}

// BindPlayerRPC 使用契约默认 ServiceName "PlayerService" 绑定轻量客户端。
func BindPlayerRPC(owner service.IService) PlayerRPCClient {
	return NewPlayerRPCClient(owner, rpc.ToService("PlayerService"))
}

// BindPlayerRPCTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindPlayerRPCTo(owner service.IService, serviceName string) PlayerRPCClient {
	return NewPlayerRPCClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client PlayerRPCClient) OnNode(nodeID string) PlayerRPCClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client PlayerRPCClient) RouteRoundRobin() PlayerRPCClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client PlayerRPCClient) RouteRandom() PlayerRPCClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client PlayerRPCClient) Route(key any) PlayerRPCClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client PlayerRPCClient) RouteBy(selector rpc.RouteSelector) PlayerRPCClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client PlayerRPCClient) IncludeRetired() PlayerRPCClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodePlayerRPCGetPlayerRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCGetPlayerRequest(client rpc.Client, kind rpc.CallKind, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCGetPlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// encodePlayerRPCGetPlayerResponse 计算并一次写入当前方法响应载荷。
func encodePlayerRPCGetPlayerResponse(response *rpc.ResponseWriter, result1 string) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1)); err != nil {
		return err
	}
	return writer.Done()
}

// decodePlayerRPCGetPlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCGetPlayerResponse(data []byte) (result1 string, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1 = string(decoded1)
	decodeErr = reader.Done()
	return
}

// AwaitGetPlayer 以顺序编程外观等待 RPC 结果。
func (client PlayerRPCClient) AwaitGetPlayer(ctx context.Context, arg1 int64) (result1 string, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, playerRPCGetPlayerMethodID, request, func(data []byte) error {
		result1, err = decodePlayerRPCGetPlayerResponse(data)
		return err
	})
	return
}

// AsyncGetPlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client PlayerRPCClient) AsyncGetPlayer(ctx context.Context, arg1 int64, callback func(context.Context, string, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Async(ctx, playerRPCGetPlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(string), callErr)
			return
		}
		result1, decodeErr := decodePlayerRPCGetPlayerResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyGetPlayer(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCGetPlayerMethodID, request)
}

// BroadcastGetPlayer 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastGetPlayer(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, playerRPCGetPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCGetPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, playerRPCGetPlayerMethodID, request)
}

// encodePlayerRPCRefreshRequest 计算并一次写入当前方法请求载荷。
func encodePlayerRPCRefreshRequest(client rpc.Client, kind rpc.CallKind, arg1 int64) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt64(int64(arg1)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodePlayerRPCRefreshRequest 按固定契约顺序解码并校验完整载荷。
func decodePlayerRPCRefreshRequest(data []byte) (arg1 int64, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int64
	decoded1, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1 = int64(decoded1)
	decodeErr = reader.Done()
	return
}

// NotifyRefresh 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) NotifyRefresh(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareNotify(ctx, playerRPCRefreshMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRefreshRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, playerRPCRefreshMethodID, request)
}

// BroadcastRefresh 提交通知并主动放弃业务结果。
func (client PlayerRPCClient) BroadcastRefresh(ctx context.Context, arg1 int64) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, playerRPCRefreshMethodID)
	if err != nil {
		return err
	}
	request, err := encodePlayerRPCRefreshRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, playerRPCRefreshMethodID, request)
}

// playerRPCDispatcher 把 MethodID 静态分派到 PlayerRPC 实现。
type playerRPCDispatcher struct{ impl PlayerRPC }

// NewPlayerRPCDispatcher 创建不使用反射的静态 Dispatcher。
func NewPlayerRPCDispatcher(impl PlayerRPC) rpc.Dispatcher {
	return &playerRPCDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *playerRPCDispatcher) ContractID() rpc.ContractID { return playerRPCContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *playerRPCDispatcher) Fingerprint() rpc.ContractFingerprint {
	return playerRPCFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *playerRPCDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case playerRPCGetPlayerMethodID:
		arg1, err := decodePlayerRPCGetPlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.GetPlayer(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.GetPlayer(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodePlayerRPCGetPlayerResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case playerRPCRefreshMethodID:
		arg1, err := decodePlayerRPCRefreshRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			dispatcher.impl.Refresh(ctx, arg1)
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		return response, errs.ErrInvalidArgument
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

// RPCDispatcher 由 origingen 生成，使 Node 无需业务注册样板即可发现 github.com/duanhf2012/origin/v3/examples/_support/tutorialrpc.PlayerRPC。
func (service *PlayerService) RPCDispatcher() rpc.Dispatcher {
	return NewPlayerRPCDispatcher(service)
}
